# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YOhUVCrBT9bcHG7WkQAT9OtDdhzil541
"""

# Cài đặt thư viện giao diện và import tensorflow-datasets
!pip install -q gradio tensorflow-datasets

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
import tensorflow_datasets as tfds

# ==============================================================================
# MODULE 1: TÍCH HỢP VÀ TIỀN XỬ LÝ DỮ LIỆU (DATA INTEGRATION & PREPROCESSING)
# Sử dụng TensorFlow Datasets để đảm bảo không bị lỗi "not a zip file"
# ==============================================================================

def load_and_preprocess_data():
    """
    Hàm này chịu trách nhiệm:
    1. Tải bộ dữ liệu EMNIST (chữ cái A-Z) thông qua TFDS (ổn định hơn).
    2. Chuyển đổi nhãn (labels) về định dạng chuẩn (0 - 25).
    3. Xoay và lật ảnh (EMNIST mặc định bị xoay 90 độ và lật ngược).
    4. Chuẩn hóa giá trị pixel (từ 0-255 về 0-1).
    """
    print("Đang tải bộ dữ liệu EMNIST (Letters) từ server Google... Vui lòng đợi chút nhé.")

    # Tải dữ liệu toàn bộ vào bộ nhớ (batch_size=-1)
    ds_train, ds_test = tfds.load('emnist/letters', split=['train', 'test'], batch_size=-1, as_supervised=True)

    # Chuyển đổi tensor sang numpy array để dễ xử lý
    X_train, y_train = tfds.as_numpy(ds_train)
    X_test, y_test = tfds.as_numpy(ds_test)

    # Ảnh từ TFDS có shape (N, 28, 28, 1), ta cần loại bỏ chiều cuối (số 1) để thành (N, 28, 28)
    X_train = np.squeeze(X_train)
    X_test = np.squeeze(X_test)

    print(f"Kích thước tập huấn luyện ban đầu: {X_train.shape}")
    print(f"Kích thước tập kiểm thử ban đầu: {X_test.shape}")

    # Nhãn của EMNIST letters bắt đầu từ 1 (A=1, B=2...). Ta trừ đi 1 để bắt đầu từ 0 (A=0) cho Keras.
    y_train = y_train - 1
    y_test = y_test - 1

    # Định hướng lại ảnh: Cần transpose lại để ảnh không bị lộn ngược và xoay ngang.
    X_train = np.transpose(X_train, (0, 2, 1))
    X_test = np.transpose(X_test, (0, 2, 1))

    # Ép kiểu và chuẩn hóa pixel về [0, 1]
    X_train = X_train.astype('float32') / 255.0
    X_test = X_test.astype('float32') / 255.0

    print("Hoàn tất tiền xử lý dữ liệu!")
    return (X_train, y_train), (X_test, y_test)

# Chạy module dữ liệu
(X_train, y_train), (X_test, y_test) = load_and_preprocess_data()

# ==============================================================================
# MODULE 2: XÂY DỰNG VÀ HUẤN LUYỆN MÔ HÌNH ANN (MODEL TRAINING MODULE)
# ==============================================================================

def build_ann_model():
    """
    Xây dựng kiến trúc Mạng nơ-ron nhân tạo (ANN) tuần tự.
    Cam kết CHỈ dùng Flatten và Dense, không dùng Conv2D (CNN).
    """
    model = Sequential([
        # Lớp đầu vào: Dàn phẳng ảnh 2D (28x28) thành mảng 1D (784 điểm ảnh)
        Flatten(input_shape=(28, 28), name="Input_Flatten"),

        # Lớp ẩn thứ nhất (Hidden Layer 1)
        Dense(512, activation='relu', name="Hidden_1"),
        BatchNormalization(),
        Dropout(0.3), # Bỏ qua ngẫu nhiên 30% nơ-ron để tránh học vẹt

        # Lớp ẩn thứ hai (Hidden Layer 2)
        Dense(256, activation='relu', name="Hidden_2"),
        BatchNormalization(),
        Dropout(0.3),

        # Lớp ẩn thứ ba (Hidden Layer 3)
        Dense(128, activation='relu', name="Hidden_3"),
        BatchNormalization(),
        Dropout(0.2),

        # Lớp đầu ra (Output Layer): 26 nơ-ron tương ứng 26 chữ cái (A-Z)
        Dense(26, activation='softmax', name="Output_Layer")
    ])

    # Biên dịch mô hình
    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

def train_model(model, X_train, y_train, X_test, y_test):
    """
    Tiến hành huấn luyện với các chiến lược tối ưu để đạt độ chính xác cao nhất.
    """
    print("\nBắt đầu quá trình huấn luyện mạng ANN...")

    # Dừng sớm nếu mô hình không tiến bộ sau 5 epoch
    early_stop = EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True)

    # Giảm learning rate nếu quá trình học bị chững lại
    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=0.00001)

    history = model.fit(
        X_train, y_train,
        validation_data=(X_test, y_test),
        epochs=20, # Có thể tự dừng sớm nhờ EarlyStopping
        batch_size=256,
        callbacks=[early_stop, reduce_lr],
        verbose=1
    )

    # Đánh giá lại mô hình trên tập test
    test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
    print(f"\n=> Huấn luyện hoàn tất! Độ chính xác trên tập kiểm thử (Test Accuracy): {test_acc*100:.2f}%")

    # Lưu mô hình để App sử dụng
    model.save('ann_letter_model.h5')
    print("Đã lưu mô hình thành công vào file 'ann_letter_model.h5'.")
    return model, history

# Khởi tạo và bắt đầu huấn luyện
ann_model = build_ann_model()
ann_model.summary()
trained_model, training_history = train_model(ann_model, X_train, y_train, X_test, y_test)
from google.colab import drive
import shutil

# 1. Yêu cầu quyền truy cập Google Drive của bạn
drive.mount('/content/drive')

# 2. Copy file mô hình từ Colab sang Drive để lưu vĩnh viễn
# Bạn có thể đổi tên thư mục 'MyDrive' thành nơi bạn muốn lưu
shutil.copy('ann_letter_model.h5', '/content/drive/MyDrive/ann_letter_model.h5')
print("Đã lưu mô hình an toàn vào Google Drive!")

import gradio as gr
import cv2
import numpy as np
from tensorflow.keras.models import load_model
from google.colab import drive

# 1. Kết nối Google Drive để lấy mô hình
drive.mount('/content/drive')

# 2. Tải trực tiếp mô hình
model_path = '/content/drive/MyDrive/ann_letter_model.h5'
try:
    trained_model = load_model(model_path)
    print("✅ Đã tải mô hình thành công từ Google Drive! Sẵn sàng chạy.")
except Exception as e:
    print(f"❌ Lỗi: Không tìm thấy mô hình tại {model_path}. Vui lòng kiểm tra lại.")

# Nhãn dán từ A đến Z
LABELS = [chr(i) for i in range(ord('A'), ord('Z') + 1)]

# 3. Hàm tiền xử lý ảnh
def preprocess_user_image(image):
    if image is None: return None
    if isinstance(image, dict):
        image = image.get('composite')
        if image is None: return None

    # Xử lý màu sắc và nền trong suốt
    if len(image.shape) == 3:
        if image.shape[2] == 4:
            alpha = image[:, :, 3] / 255.0
            rgb = image[:, :, :3]
            bg = np.ones_like(rgb, dtype=np.uint8) * 255
            image = (rgb * alpha[:, :, np.newaxis] + bg * (1 - alpha[:, :, np.newaxis])).astype(np.uint8)
        gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY) if len(image.shape) == 3 else image[:, :, 0]
    else:
        gray = image

    # Lật màu nền nếu cần
    bg_color = np.median(np.concatenate([gray[0,:], gray[-1,:], gray[:,0], gray[:,-1]]))
    if bg_color > 127: gray = cv2.bitwise_not(gray)

    # Cắt gọn nét vẽ
    coords = cv2.findNonZero(gray)
    if coords is not None:
        x, y, w, h = cv2.boundingRect(coords)
        pad = max(w, h) // 4
        x, y = max(0, x - pad), max(0, y - pad)
        w, h = min(gray.shape[1] - x, w + 2*pad), min(gray.shape[0] - y, h + 2*pad)
        gray = gray[y:y+h, x:x+w]
    else: return None

    # Đưa về chuẩn đầu vào
    resized = cv2.GaussianBlur(cv2.resize(gray, (28, 28), interpolation=cv2.INTER_AREA), (3, 3), 0)
    return np.expand_dims(resized.astype('float32') / 255.0, axis=0)

# 4. Hàm dự đoán
def predict_letter(image):
    try:
        tensor = preprocess_user_image(image)
        if tensor is None:
            return {"Chưa có nét vẽ. Vui lòng thử lại!": 1.0}

        prediction = trained_model.predict(tensor, verbose=0)[0]
        best_idx = np.argmax(prediction)

        if float(prediction[best_idx]) < 0.5:
            return {f"⚠️ Không rõ chữ gì ({float(prediction[best_idx])*100:.1f}%). Vui lòng vẽ rõ hơn!": 1.0}

        return {LABELS[i]: float(prediction[i]) for i in np.argsort(prediction)[-3:][::-1]}
    except Exception as e:
        return {f"Lỗi hệ thống: {str(e)}": 0.0}

# 5. Khởi chạy Giao diện Tiếng Việt 100%
with gr.Blocks(theme=gr.themes.Soft()) as app:
    gr.Markdown("<center><h1>🔠 AI Alphabet Recognition</h1></center>")

    with gr.Tabs():
        # Phân vùng 1: Bảng vẽ
        with gr.TabItem("🖌️ Vẽ Trực Tiếp"):
            with gr.Row():
                with gr.Column():
                    canvas_input = gr.Sketchpad(label="Hãy vẽ một chữ cái vào bảng dưới đây", type="numpy")
                    with gr.Row():
                        btn_clear_canvas = gr.Button("🗑️ Xóa hình")
                        btn_predict_canvas = gr.Button("🔍 Nhận diện", variant="primary")
                with gr.Column():
                    canvas_output = gr.Label(num_top_classes=3, label="Kết quả dự đoán (Kèm mức độ tin cậy)")

            # Gắn lệnh cho nút bấm
            btn_predict_canvas.click(fn=predict_letter, inputs=canvas_input, outputs=canvas_output)
            btn_clear_canvas.click(lambda: None, None, canvas_input)

        # Phân vùng 2: Tải ảnh có sẵn
        with gr.TabItem("🖼️ Tải Ảnh Lên"):
            with gr.Row():
                with gr.Column():
                    image_input = gr.Image(label="Kéo thả hoặc nhấn vào đây để tải ảnh", type="numpy")
                    with gr.Row():
                        btn_clear_image = gr.Button("🗑️ Xóa ảnh")
                        btn_predict_image = gr.Button("🔍 Nhận diện", variant="primary")
                with gr.Column():
                    image_output = gr.Label(num_top_classes=3, label="Kết quả dự đoán (Kèm mức độ tin cậy)")

            # Gắn lệnh cho nút bấm
            btn_predict_image.click(fn=predict_letter, inputs=image_input, outputs=image_output)
            btn_clear_image.click(lambda: None, None, image_input)

app.launch(debug=True, share=True)

trained_model.save('ann_letter_model.h5')